"""Initial batch tables

Revision ID: cff2a2c1c2d3
Revises: 
Create Date: 2025-08-31 13:10:42.728589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff2a2c1c2d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qc_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qc_batch_id', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('process', sa.String(), nullable=False),
    sa.Column('process_step', sa.String(), nullable=False),
    sa.Column('qc_batch_end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qc_batch_id')
    )
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('process', sa.String(), nullable=False),
    sa.Column('process_step', sa.String(), nullable=False),
    sa.Column('qc_batch_id', sa.String(), nullable=True),
    sa.Column('process_batch_end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qc_batch_id'], ['qc_batches.qc_batch_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batches')
    op.drop_table('qc_batches')
    # ### end Alembic commands ###
